"""
Save a tokenizer for veRL with the custom DeepSeek chat template.

The chat template ensures <think> is in the completion (not prefill),
which is critical for the format reward to work correctly. Also adds
<bigmodel> and </bigmodel> as special tokens and sets pad_token = eos_token.

Usage:
    python verl_training/prepare_tokenizer.py \
        --model akhauriyash/DeepSeek-R1-Distill-Qwen-1.5B-SpeculativeReasoner \
        --output_dir ~/data/splitreason/tokenizer
"""

import argparse
import os

from transformers import AutoTokenizer

# Custom DeepSeek chat template from config_demo.yaml line 10.
# Key property: <think> is NOT part of prefill — the model generates it.
CHAT_TEMPLATE = (
    "{% if not add_generation_prompt is defined %}"
    "{% set add_generation_prompt = false %}"
    "{% endif %}"
    "{% set ns = namespace(is_first=false, is_tool=false, is_output_first=true, system_prompt='') %}"
    "{%- for message in messages %}"
    "{%- if message['role'] == 'system' %}"
    "{% set ns.system_prompt = message['content'] %}"
    "{%- endif %}"
    "{%- endfor %}"
    "{{bos_token}}{{ns.system_prompt}}"
    "{%- for message in messages %}"
    "{%- if message['role'] == 'user' %}"
    "{%- set ns.is_tool = false -%}"
    "{{'<｜User｜>' + message['content']}}"
    "{%- endif %}"
    "{%- if message['role'] == 'assistant' and message['content'] is none %}"
    "{%- set ns.is_tool = false -%}"
    "{%- for tool in message['tool_calls']%}"
    "{%- if not ns.is_first %}"
    "{{'<｜Assistant｜><｜tool▁calls▁begin｜><｜tool▁call▁begin｜>' + tool['type'] + '<｜tool▁sep｜>' + tool['function']['name'] + '\\n' + '```json' + '\\n' + tool['function']['arguments'] + '\\n' + '```' + '<｜tool▁call▁end｜>'}}"
    "{%- set ns.is_first = true -%}"
    "{%- else %}"
    "{{'\\n' + '<｜tool▁call▁begin｜>' + tool['type'] + '<｜tool▁sep｜>' + tool['function']['name'] + '\\n' + '```json' + '\\n' + tool['function']['arguments'] + '\\n' + '```' + '<｜tool▁call▁end｜>'}}"
    "{{'<｜tool▁calls▁end｜><｜end▁of▁sentence｜>'}}"
    "{%- endif %}"
    "{%- endfor %}"
    "{%- endif %}"
    "{%- if message['role'] == 'assistant' and message['content'] is not none %}"
    "{%- if ns.is_tool %}"
    "{{'<｜tool▁outputs▁end｜>' + message['content'] + '<｜end▁of▁sentence｜>'}}"
    "{%- set ns.is_tool = false -%}"
    "{%- else %}"
    "{% set content = message['content'] %}"
    "{{'<｜Assistant｜>' + content + '<｜end▁of▁sentence｜>'}}"
    "{%- endif %}"
    "{%- endif %}"
    "{%- if message['role'] == 'tool' %}"
    "{%- set ns.is_tool = true -%}"
    "{%- if ns.is_output_first %}"
    "{{'<｜tool▁outputs▁begin｜><｜tool▁output▁begin｜>' + message['content'] + '<｜tool▁output▁end｜>'}}"
    "{%- set ns.is_output_first = false %}"
    "{%- else %}"
    "{{'\\n<｜tool▁output▁begin｜>' + message['content'] + '<｜tool▁output▁end｜>'}}"
    "{%- endif %}"
    "{%- endif %}"
    "{%- endfor -%}"
    "{% if ns.is_tool %}{{'<｜tool▁outputs▁end｜>'}}{% endif %}"
    "{% if add_generation_prompt and not ns.is_tool %}{{'<｜Assistant｜>'}}{% endif %}"
)


def main():
    parser = argparse.ArgumentParser(description="Prepare tokenizer for veRL training")
    parser.add_argument(
        "--model",
        type=str,
        default="akhauriyash/DeepSeek-R1-Distill-Qwen-1.5B-SpeculativeReasoner",
    )
    parser.add_argument(
        "--output_dir",
        type=str,
        default=os.path.expanduser("~/data/splitreason/tokenizer"),
    )
    args = parser.parse_args()

    print(f"Loading tokenizer from {args.model}")
    tokenizer = AutoTokenizer.from_pretrained(args.model, trust_remote_code=True)

    # Set custom chat template
    tokenizer.chat_template = CHAT_TEMPLATE

    # Set pad_token = eos_token
    tokenizer.pad_token = tokenizer.eos_token

    # Add <bigmodel> and </bigmodel> as special tokens
    special_tokens = {"additional_special_tokens": ["<bigmodel>", "</bigmodel>"]}
    num_added = tokenizer.add_special_tokens(special_tokens)
    print(f"Added {num_added} special tokens: <bigmodel>, </bigmodel>")

    # Verify tokenization
    test_str = "hi <bigmodel> some text </bigmodel> done"
    tokens = tokenizer.tokenize(test_str, add_special_tokens=True)
    token_ids = tokenizer.convert_tokens_to_ids(tokens)
    print("\nTokenization test:")
    for tok, tid in zip(tokens, token_ids):
        print(f"  {tok:<20} {tid}")

    # Verify chat template produces <think> in completion
    messages = [
        {"role": "system", "content": "You are helpful."},
        {"role": "user", "content": "What is 2+2?"},
    ]
    formatted = tokenizer.apply_chat_template(messages, add_generation_prompt=True, tokenize=False)
    print(f"\nChat template output:\n{formatted}")
    assert "<think>" not in formatted, "ERROR: <think> should NOT be in the prompt template"
    print("OK: <think> is not in the prefill (will be generated by model)")

    # Save
    os.makedirs(args.output_dir, exist_ok=True)
    tokenizer.save_pretrained(args.output_dir)
    print(f"\nTokenizer saved to {args.output_dir}")


if __name__ == "__main__":
    main()
