"""
Save a tokenizer for router training with custom DeepSeek chat template.

Unlike the speculative reasoning tokenizer, this does NOT add <bigmodel>/
</bigmodel> special tokens since the router makes decisions externally.

The chat template ensures <think> is in the completion (not prefill),
which is critical for the format reward to work correctly.

Usage:
    python router/prepare_tokenizer.py --output_dir ~/data/splitreason/tokenizer_router
"""

import argparse
import os

from transformers import AutoTokenizer

# Custom DeepSeek chat template.
# Key property: <think> is NOT part of prefill — the model generates it.
CHAT_TEMPLATE = (
    "{% if not add_generation_prompt is defined %}"
    "{% set add_generation_prompt = false %}"
    "{% endif %}"
    "{% set ns = namespace(is_first=false, is_tool=false, is_output_first=true, system_prompt='') %}"
    "{%- for message in messages %}"
    "{%- if message['role'] == 'system' %}"
    "{% set ns.system_prompt = message['content'] %}"
    "{%- endif %}"
    "{%- endfor %}"
    "{{bos_token}}{{ns.system_prompt}}"
    "{%- for message in messages %}"
    "{%- if message['role'] == 'user' %}"
    "{%- set ns.is_tool = false -%}"
    "{{'<\uff5cUser\uff5c>' + message['content']}}"
    "{%- endif %}"
    "{%- if message['role'] == 'assistant' and message['content'] is none %}"
    "{%- set ns.is_tool = false -%}"
    "{%- for tool in message['tool_calls']%}"
    "{%- if not ns.is_first %}"
    "{{'<\uff5cAssistant\uff5c><\uff5ctool\u2581calls\u2581begin\uff5c><\uff5ctool\u2581call\u2581begin\uff5c>' + tool['type'] + '<\uff5ctool\u2581sep\uff5c>' + tool['function']['name'] + '\\n' + '```json' + '\\n' + tool['function']['arguments'] + '\\n' + '```' + '<\uff5ctool\u2581call\u2581end\uff5c>'}}"
    "{%- set ns.is_first = true -%}"
    "{%- else %}"
    "{{'\\n' + '<\uff5ctool\u2581call\u2581begin\uff5c>' + tool['type'] + '<\uff5ctool\u2581sep\uff5c>' + tool['function']['name'] + '\\n' + '```json' + '\\n' + tool['function']['arguments'] + '\\n' + '```' + '<\uff5ctool\u2581call\u2581end\uff5c>'}}"
    "{{'<\uff5ctool\u2581calls\u2581end\uff5c><\uff5cend\u2581of\u2581sentence\uff5c>'}}"
    "{%- endif %}"
    "{%- endfor %}"
    "{%- endif %}"
    "{%- if message['role'] == 'assistant' and message['content'] is not none %}"
    "{%- if ns.is_tool %}"
    "{{'<\uff5ctool\u2581outputs\u2581end\uff5c>' + message['content'] + '<\uff5cend\u2581of\u2581sentence\uff5c>'}}"
    "{%- set ns.is_tool = false -%}"
    "{%- else %}"
    "{% set content = message['content'] %}"
    "{{'<\uff5cAssistant\uff5c>' + content + '<\uff5cend\u2581of\u2581sentence\uff5c>'}}"
    "{%- endif %}"
    "{%- endif %}"
    "{%- if message['role'] == 'tool' %}"
    "{%- set ns.is_tool = true -%}"
    "{%- if ns.is_output_first %}"
    "{{'<\uff5ctool\u2581outputs\u2581begin\uff5c><\uff5ctool\u2581output\u2581begin\uff5c>' + message['content'] + '<\uff5ctool\u2581output\u2581end\uff5c>'}}"
    "{%- set ns.is_output_first = false %}"
    "{%- else %}"
    "{{'\\n<\uff5ctool\u2581output\u2581begin\uff5c>' + message['content'] + '<\uff5ctool\u2581output\u2581end\uff5c>'}}"
    "{%- endif %}"
    "{%- endif %}"
    "{%- endfor -%}"
    "{% if ns.is_tool %}{{'<\uff5ctool\u2581outputs\u2581end\uff5c>'}}{% endif %}"
    "{% if add_generation_prompt and not ns.is_tool %}{{'<\uff5cAssistant\uff5c>'}}{% endif %}"
)


def main():
    parser = argparse.ArgumentParser(description="Prepare tokenizer for router training")
    parser.add_argument(
        "--model",
        type=str,
        default="deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B",
    )
    parser.add_argument(
        "--output_dir",
        type=str,
        default=os.path.expanduser("~/data/splitreason/tokenizer_router"),
    )
    args = parser.parse_args()

    print(f"Loading tokenizer from {args.model}")
    tokenizer = AutoTokenizer.from_pretrained(args.model, trust_remote_code=True)

    # Set custom chat template
    tokenizer.chat_template = CHAT_TEMPLATE

    # Set pad_token = eos_token
    tokenizer.pad_token = tokenizer.eos_token

    # NO special tokens added — router decisions are external to the model

    # Verify chat template produces <think> in completion
    messages = [
        {"role": "system", "content": "You are helpful."},
        {"role": "user", "content": "What is 2+2?"},
    ]
    formatted = tokenizer.apply_chat_template(messages, add_generation_prompt=True, tokenize=False)
    print(f"\nChat template output:\n{formatted}")
    assert "<think>" not in formatted, "ERROR: <think> should NOT be in the prompt template"
    print("OK: <think> is not in the prefill (will be generated by model)")

    # Save
    os.makedirs(args.output_dir, exist_ok=True)
    tokenizer.save_pretrained(args.output_dir)
    print(f"\nTokenizer saved to {args.output_dir}")


if __name__ == "__main__":
    main()
